from tkinter import *
# import tkinter as tk
root =Tk()
root.title('Facebook log in')
root.geometry('1000x600')
frame1=Frame(root,width=400,height=350,border=1,bg='white',relief='flat')
frame1.place(x=750,y=220)
uname=Text(frame1,width=41,height=2,relief='solid',font=('Helvetica',13,'normal'))
uname.place(x=12,y=20)
pword=Text(frame1,width=41,height=2,relief='solid',font=('Helvetica',13,'normal'))
pword.place(x=12,y=72)
log_btn=Button(frame1,text='Login',bg='royalblue',fg='white',font=('Helvetica',13,'bold'),width=36,height=2,relief='flat')
log_btn.place(x=13,y=155)
fg_btn=Button(frame1,text='Forgot Password?',bg='white',fg='royalblue',font=('courierNew',12,'normal'),relief='flat',)
fg_btn.place(x=145,y=250)
frame2=Frame(root,width=400,height=100,bg='white',relief='flat')
frame2.place(x=750,y=573)
creat_btn=Button(frame2,width=20,height=2,text='Create new account',font=('Helvetica',13,'bold'),bg='limegreen',fg='white',relief='flat')
creat_btn.place(x=100,y=25)
fb=Label(root,text='facebook',font=('arial',50,'bold'),fg='royalblue')
fb.place(x=150,y=300)
stmt=Label(root,text=f'Connect with friends and the world \naround you on Facebook',font=('arial',20,),justify='left')
stmt.place(x=150,y=370)
root.mainloop()